### ISSUE TITLE
Versioning Dossiers

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#101]
_**As a user, I'd like to be able to track all versions of each packages and requests I contributed to or been assigned to by my colleagues.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 10 hr]
[SP: 10]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] Create front-end page to view all versions for a package.
- [x] Come up with an optimal design for handling dynamic updates to dossiers.
- [x] Implement versioning functionality to back-end.
- [x] Refactor any repository calls to include versioning for dossiers.
- [x] Verify versioning by editing packages in pipelines.
- [x] ~Add revert functionality.~

-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | From the Package page, press "View all Revisions" on any available package | Routed to the Revisions page for that package, displaying all the revisions, their modification date/author and pdf document  | Routed to the Revisions page for that package, displaying all the revisions, their modification date/author and pdf document  | Success

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
