### ISSUE TITLE
Program Requests

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#105]
_**As a user, I'd like to be able to add, edit and remove programs and have them be added to existing packages and generated into pdf files along with course requests.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 14 hr]
[SP: 14]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] Implement program requests endpoints.
- [x] Implement program request front-end and back-end.
- [x] ~Add program requests to impact statements.~ (already implemented by @BarsemianGeorgik )
- [x] Add program requests to pdf generator.

-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User navigates to course edit-form. | edit-form is displayed with degree/core component. | edit-form is displayed with degree/core component. | Success
| 2 | User changes or adds/removes degree/core and submits. Then, user navigates to dossier Pdf | Dossier pdf displays program pages. | Dossier pdf displays program pages.  | Success

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
