### ISSUE TITLE
Academic Calendar Design & Integration

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#106]
_**As a user, I'd like to be able to know what sections of the academic calendar my requests will affect. I should also be able to base my requests from the academic calendar.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 12 hr]
[SP: 12]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] Design a solution to have Calendar mapped to each entity in CMS.
- [x] Implement Section model
- [x] Add sample Section data to the database
- [x] Implement Calendar sections to impact reports.
- [x] Implement Calendar sections to pdf generator. 
- [x] ~Add Calendar support to client UI to navigate and choose a section to edit.~ (out of scope?) 
-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 |  User navigates to edit-form and clicks on impact statement | Calendar sections is displayed.  | Calendar sections is displayed.  | Success
| 2 | User views dossier pdf. | Calendar sections is displayed.  | Calendar sections is displayed. | Success

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
