### ISSUE TITLE
Hide tracking until pipeline is selected

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#116]
- [x] Progress should be renamed to Package Tracking.
- [x] Boolean isTracked should be stored. Becomes true when "submit for approval" is selected.
- [x] Tracking page should be hidden as long as isTracked is false.

[Risk: Medium]
[Priority: Medium]
[Ideal-Time: 1 hr]
[SP: 1]
