### ISSUE TITLE
Package Pipeline tracking - Approver Perspective 

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#117]
_**As a package approver, I'd like to receive my designated packages on my cms homepage. I should be able to view its pdf, make edits, and have the option to Accept/Decline the package requests. I should also be able to convey my feedback (rationale) as a supporting document appended to the package.**_

Academic Bodies who can't edit the package might not need a cms user page. Their user story can be completed through emailing the package pdf file and an embedded option to Accept/Decline.

This is a follow-up story from story #25. The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 8 hr]
[SP: 8]

-------------------------------------------------------------------------------------------------------------

**Tasks** 
- [x] Add approver homepage. [3 SP]
- [x] Connect pipeline mechanism to the above page. [4 SP]
- [x] Test pipeline tracking. [1 SP]
-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User clicks the 'Approve' button for a package that is awaiting approval | The package moves on for approval by the next approving body and its position in the tracker is updated | The package moves on for approval by the next approving body and its position in the tracker is updated | Success |
| 2 | User clicks the 'Decline' button for a package that is awaiting approval | The package no longer has its position in the pipeline being tracked | The package no longer has its position in the pipeline being tracked | Success | 

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
