### ISSUE TITLE
English and French Spell-Grammar Checkers

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#118]
_**As a user, I'd like to have an English and French spell and grammar checkers available when making requests to increase the readability and clarity of my proposals.**_

The following is required to complete this story:

1. front-end implementation
2. test-cases
3. demo-steps
4. stakeholder sign-off

[Risk: Medium]
[Priority: High]
[Ideal-Time: 10 hr]
[SP: 10]

-------------------------------------------------------------------------------------------------------------

**Tasks** 
- [x] Add Mockup to wiki and issue (as comment).
- [x] Add spell check support to client UI on edit pages.
- [x] Add grammar checker support to client UI on edit pages.
-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | Type an incorrect word | red line appears under the word | same as expected| n/a
| 2 | Right click the word | different suggestions appear under the word with option to add it to dictionary | same as expected | word can be corrected or added to dictionary.

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
