### ISSUE TITLE
Add/Remove course requests

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#127]
_**As a user, I'd like to be able to be able to remove existing courses and add new courses.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 10 hr]
[SP: 10]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] course-add form (same as edit, but empty fields)
- [x] course-remove form (or button beside search results + rationale, resource impl, other)
- [x] connect to backend api
- [x] course-add functionality backend.
- [x] course-remove functionality backend.
-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User clicks on "create new request". | Redirected to search page with new course icon. | Redirected to search page with new course icon. | Success
| 2.1 | User clicks on "create new course". |  Redirected to create course-form. | Redirected to create course-form. | Success
| 2.2 | User clicks on an existing course. |  Redirected to course edit-form. | Redirected to course edit-form. | Success
| 3 | User clicks on "delete course". |  Redirected to homepage with course-removal request added. | Redirected to homepage with course-removal request added. | Success

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
