### ISSUE TITLE
Section 70719 Requests

### ISSUE THREAD

**Issue by BarsemianGeorgik** [Keeran10/CurriculumManagementSystem#182]
_**As a user, I'd like to be able to add, edit and remove calendars and have them be added to existing packages and generated into pdf files along with course and program requests.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 10 hr]
[SP: 23]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] Implement calendar requests endpoints.
- [x] Implement calendar request front-end.
- [x] Implement calendar request back-end.
- [x] ~Add calendar requests to impact statements.~
- [x] Add calendar requests to pdf generator.
Tasks: #183

-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User navigates to section edit-form. | section edit-form displayed. | section edit-form displayed. | Success
| 2 | User modifies section and views dossier pdf. | section page displayed on pdf. | section page displayed on pdf. | Success

-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
