### ISSUE TITLE
Calendar Expansion

### ISSUE THREAD

**Issue by BarsemianGeorgik** [Keeran10/CurriculumManagementSystem#230]
_**As a user, I'd like to be able to add, edit and remove calendars for the entire Software engineering, computer science and mechanical programs and have them be added to existing packages and generated into pdf files along with course and program requests.**_

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

[Risk: High]
[Priority: High]
[Ideal-Time: 30 hr]
[SP: 35]

-------------------------------------------------------------------------------------------------------------

**Tasks**
- [x] Implement calendar requests endpoints.
- [x] Implement calendar request front-end.
- [x] Implement calendar request back-end.
- [x] ~Add calendar requests to impact statements.~
- [x] Add calendar requests to pdf generator.

related Tasks: #231, #232  

-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User clicks on the homepage calendar link. | Redirected to calendar table of content. | Redirected to calendar table of content. | Success
| 2 | User clicks on a section from the table of content. | Redirected to section edit-form. | Redirected to section edit-form. | Success
-------------------------------------------------------------------------------------------------------------

**Story approved by stakeholder Dr. Akgunduz.**
