### ISSUE TITLE
Recent Trends feature

### ISSUE THREAD

**Issue by Keeran10** [Keeran10/CurriculumManagementSystem#241]
_**As a user, I would like to know if my requested calendar changes align with the recent trends in my domain.**_

This story can be implemented through a "check recent trends" button on the edit-forms. On click, we crawl the web/news/social media to find relevant articles and statistics with respect to the requested changes and display the top headlines/statistics to the user just like we did with impact report. 

The following is required to complete this story:

1. front-end implementation
2. back-end implementation
3. test-cases
4. demo-steps
5. stakeholder sign-off

Tasks #260, #262 , #263 
[Risk: Medium]
[Priority: High]
[Ideal-Time: 30 hr]
[SP: 40]

-------------------------------------------------------------------------------------------------------------
**tasks:**
- [x] News API implementation.
- [x] Trend heuristics development.
- [x] "check trends" UI button + functionality (front-end).
-------------------------------------------------------------------------------------------------------------

**Demo-steps & Acceptance-test**
This test characterizes the desired behavior for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User clicks on course edit-form. | edit-form is displayed. | edit-form is displayed. | Success |
| 2 | User clicks on `check trends`. | check-trends dialogue is opened. | check-trends dialogue is opened. | Success |
-------------------------------------------------------------------------------------------------------------

**Story approved by Dr. Shihab.**
