### ISSUE TITLE
UI rehaul #3 Feature

### ISSUE THREAD

**Issue by soenAnt** [Keeran10/CurriculumManagementSystem#256]
_**As a user, I would like to have a user friendly, expandable, and appealing user interface that is consistent among different screen sizes..**_

This story completely revamps the UI to introduce a different structure to the front-end in terms of placement of items on the pages as well as a complete cosmetic rehaul and additions of new elements that can be expanded later on and filled out with actual features and/or links.

The following is required to complete this story:

1. front-end login + main template for other pages mock-ups.
2. Cosmetic changes including the color palette used. 
3. Adding new material components to the front-end.
4. stakeholder sign-off

[Risk: Medium]
[Priority: High]
[Ideal-Time: 25 hr]
[SP: 41]

-------------------------------------------------------------------------------------------------------------
**tasks:**

- [x] Material Toolbar component for header/footer.
- [x] Side navbar with preferences/settings/etc. empty links.
- [x] Mat Card div in /package page needs to be differentiated from background page.
- [x] Shrink button sizes + consistency in button colors.
- [x] Icons for [x] for delete requests.
- [x] Remove header and replace with sidebar with all the buttons.
- [x] Remove "Welcome, Boris" --> Replace with profile icon.
- [x] Have a settings/account/logout buttons part of side-navbar.
- [x] Change color palette.
- [x] Tracking pipeline --> One div of content + Add sidebar.
- [x] Request package edit page (Lower upload page, remove title, fix buttons).
- [x] Dossier div title should be bold.
- [x] (optional for this iteration) Make site compatible with mobile + different screens.

related Tasks: #257, #258, #259
